created a two-hot encoding function
Eclectic-Sheep/sheeprl pull request #45
Opened 2023-06-27 13:04 UTC by DavideTr8

## Summary

Describe the purpose of the pull request, including:

A function for converting tensors representing floating point to a two-hot representation, as done in MuZero and Dreamer V3 papers.

## Type of Change

Please select the one relevant option below:

- New feature (non-breaking change that adds functionality)

## Checklist

Please confirm that the following tasks have been completed:

- [x] I have tested my changes locally and they work as expected. (Please describe the tests you performed.)
- [x] I have added unit tests for my changes, or updated existing tests if necessary.
- [x] I have updated the documentation, if applicable.
- [x] I have installed pre-commit and run locally for my code changes.

2023-06-29 08:55 UTC, belerico requested changes
I think that the implementation in the Dreamer-V3 paper is more general than this one (https://arxiv.org/abs/2301.04104). Could we adjust it?

2023-07-05 14:52 UTC, belerico submitted a review, later dismissed

2024-03-30 11:56 UTC, belerico approved these changes

2024-03-30 13:11 UTC, michele-milesi approved these changes

2024-03-30 15:37 UTC, merged